import type { Metadata } from "next";
import "../globals.css";
import { isAuthenticated } from "../utils/session";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function authLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


const isAuth = await isAuthenticated();

if(isAuth){
  redirect('/home')
}

  return (
    <div>
      {children}
    </div>
       
    
  );
}
