// app/dashboard/layout.tsx
import type { Metadata } from "next";
import "../globals.css";
import { isAuthenticated } from "@/app/utils/session";
import { redirect } from "next/navigation";
import Sidebar from "./components/sidebar";
import Header from "./components/header";
import { ThemeProvider } from "./components/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isAuth = await isAuthenticated();
  if (!isAuth) redirect("/login");

  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      <div className="flex flex-row h-screen">
        {/* Sidebar */}
        <div className="hidden md:block w-[22%] bg-[rgba(28,32,56,1)] overflow-y-auto overflow-x-hidden scrollbar-hide">
          <Sidebar />
        </div>

        {/* Main Content */}
        <div className="w-full bg-white flex flex-col overflow-hidden">
          <div className="h-16 shadow-3xl">
            <Header />
          </div>

          <div className="flex-grow bg-[rgba(241,245,249,1)] overflow-y-auto">
            {children}
          </div>
        </div>
      </div>
    </ThemeProvider>
  );
}
